[plugin]
repository = "https://github.com/Aireil/FlyTextFilter.git"
commit = "8f78a4a56f5c990c8ce87478eb0920204b7df451"
owners = [
    "Aireil",
]
project_path = "FlyTextFilter"
changelog = "Under the hood changes for adjustments and preparation for 6.3"
