[plugin]
repository = "https://github.com/Aireil/FlyTextFilter.git"
commit = "056552e34f08189b584b636ce828a757b633c8c0"
owners = [
    "Aireil",
]
project_path = "FlyTextFilter"
changelog = "Fix for 6.2 + .NET6 and API7 upgrade + split pet/chocobo in misc settings"
